require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JoinsController do

  # This should return the minimal set of attributes required to create a valid
  # Join. As you add validations to Join, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JoinsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all joins as @joins" do
      join = Join.create! valid_attributes
      get :index, {}, valid_session
      assigns(:joins).should eq([join])
    end
  end

  describe "GET show" do
    it "assigns the requested join as @join" do
      join = Join.create! valid_attributes
      get :show, {:id => join.to_param}, valid_session
      assigns(:join).should eq(join)
    end
  end

  describe "GET new" do
    it "assigns a new join as @join" do
      get :new, {}, valid_session
      assigns(:join).should be_a_new(Join)
    end
  end

  describe "GET edit" do
    it "assigns the requested join as @join" do
      join = Join.create! valid_attributes
      get :edit, {:id => join.to_param}, valid_session
      assigns(:join).should eq(join)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Join" do
        expect {
          post :create, {:join => valid_attributes}, valid_session
        }.to change(Join, :count).by(1)
      end

      it "assigns a newly created join as @join" do
        post :create, {:join => valid_attributes}, valid_session
        assigns(:join).should be_a(Join)
        assigns(:join).should be_persisted
      end

      it "redirects to the created join" do
        post :create, {:join => valid_attributes}, valid_session
        response.should redirect_to(Join.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved join as @join" do
        # Trigger the behavior that occurs when invalid params are submitted
        Join.any_instance.stub(:save).and_return(false)
        post :create, {:join => {}}, valid_session
        assigns(:join).should be_a_new(Join)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Join.any_instance.stub(:save).and_return(false)
        post :create, {:join => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested join" do
        join = Join.create! valid_attributes
        # Assuming there are no other joins in the database, this
        # specifies that the Join created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Join.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => join.to_param, :join => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested join as @join" do
        join = Join.create! valid_attributes
        put :update, {:id => join.to_param, :join => valid_attributes}, valid_session
        assigns(:join).should eq(join)
      end

      it "redirects to the join" do
        join = Join.create! valid_attributes
        put :update, {:id => join.to_param, :join => valid_attributes}, valid_session
        response.should redirect_to(join)
      end
    end

    describe "with invalid params" do
      it "assigns the join as @join" do
        join = Join.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Join.any_instance.stub(:save).and_return(false)
        put :update, {:id => join.to_param, :join => {}}, valid_session
        assigns(:join).should eq(join)
      end

      it "re-renders the 'edit' template" do
        join = Join.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Join.any_instance.stub(:save).and_return(false)
        put :update, {:id => join.to_param, :join => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested join" do
      join = Join.create! valid_attributes
      expect {
        delete :destroy, {:id => join.to_param}, valid_session
      }.to change(Join, :count).by(-1)
    end

    it "redirects to the joins list" do
      join = Join.create! valid_attributes
      delete :destroy, {:id => join.to_param}, valid_session
      response.should redirect_to(joins_url)
    end
  end

end
